### ISSUE TITLE
------ DEAD PROJECT ------

### ISSUE THREAD

**Issue by feinstein** [roughike/flutter_facebook_login#170]
I have no idea what happened to the original maintainer of this library @roughike, I hope he's in good health, but since there have been no bug fixes, upgrades, replies or PR accepted or denied, I think it's safe to assume that this library is dead and should be avoided from now on.

**Comment by Pebsie** [comment]
Such a shame as this functionality is essential for a lot of apps. I'm not sure Flutter is a viable choice without it.

**Comment by feinstein** [comment]
We can always fork it and update it ourselves, but I know it's not ideal. I hope the Firebase Auth team makes a replacement..... And hope flutter don't go the javascript way, with lots of abandoned highly-used projects.

**Comment by feinstein** [comment]
Good news, I could reach @roughike on Twitter, he appears to be fine, just not following the repo closely.

**Comment by cpboyd** [comment]
@feinstein IDK if @FirebaseExtended is the ideal place for this plugin, as they don't seem to have anything specifically targeting Facebook logins.

Ultimately, I think abandoned projects are inevitable if the project only has a single maintainer.

I definitely think there should potentially be another maintainer added to this repo in order to keep it up-to-date.

There's 11 pending PRs (granted some of them supersede others, since a few are related to SDK updates) so it's not like there's any lack of people willing to work on this project.

**Comment by feinstein** [comment]
As I said to some googlers, I think all major libraries should have someone from Google inside them as a fail-safe.

**Comment by cpboyd** [comment]
@feinstein I don't think it necessarily has to be someone from Google, but long-term libraries that need continual attention (like this one, since Facebook keeps updating their SDK to meet new iOS and Android requirements) should probably have more than one maintainer.

There are already other projects that ended up with a fork on Dart's Pub.dev.

**Comment by feinstein** [comment]
Yeah, sure there needs to have someone else... But how do you assure this will happen? Who finds volunteers? Who tries to convince maintainers that they need someone else into the project? I think Google is a good answer.

**Comment by cpboyd** [comment]
@feinstein On the other issue, someone mentioned @fluttercommunity:
https://github.com/fluttercommunity/community

Since you've already been in contact with @roughike, it might be worth seeing if he wants to transfer the repo there if he doesn't have the time to keep this plugin up-to-date.

**Comment by roughike** [comment]
I'm alive and kicking, and have no health issues. Thanks for the concern!

We're using this plugin in Reflectly in production and have about 4 million users. It works for us. That being said, I'm aware there are some bugs, the SDKs could use a little update and the pull request & issue queues need some maintenance. I guess I'm just busy doing some other stuff ¯\\_(ツ)_/¯

If someone has the context, could you describe what "dead project" means here? Unmaintained issue & PR queues, last release being ~6 months ago, or the plugin simply not working at all for you?

**Comment by feinstein** [comment]
> Unmaintained issue & PR queues, last release being ~6 months ago, or the plugin simply not working at all for you?

Well, it's actually the sum of all of it. If no-one was having troubles, opening meaningful issues or submitting PRs, it would be fine for a project to not be updated.... But once all of it comes together and there's no response, it appears to be a dead project.

I am glad you are OK, but for resilience sake it would be interesting to include someone else into the project, just as a plan B person.

**Comment by cpboyd** [comment]
@noln I'd imagine that since they're using Flutter on Google Home and for some of their mobile applications (and the looming Fuschia OS), Flutter's probably gonna be around for a while.

And dropping products isn't a uniquely "Google" thing: Microsoft dropped Windows Phone. They also were building Skype with ReactXP while pushing Xamarin as **the** way to build cross-platform apps.  Facebook is already trying to reduce scope on React Native by dropping the majority of built-in components for the community to manage instead.

There's the same risk with anything, aside from HTML and Javascript.

**Comment by eleomilagrosa** [comment]
@roughike 
Well this will be a dead project for sure.
#174 
it started since Aug 30, 2019 when App Store announce that they don't accept UIWebView anymore.
so this library will not be usable anymore because you'll get an error anyway from App Store.

**Comment by roughike** [comment]
I just merged a couple bugfix PRs and released 3.0.0 to Pub which updates the SDKs to latest versions. I'm also going through the issue tracker and closing obsolete / otherwise closeable issues.

Not sure how this is an actionable issue. You can continue the discussion here, but I'm closing this one for now, unless you have concrete action points for me. Have a great day!

**Comment by feinstein** [comment]
Thanks @roughike, glad to see this advancing :)
