### ISSUE TITLE
Pluggin does not work if there's no Facebook app installed

### ISSUE THREAD

**Issue by suesitran** [roughike/flutter_facebook_login#62]
This pluggin does not work if there's no Facebook App installed in current device. Tested on Android device and iOS simulator. The app simply failed to login. The same code works after Facebook app is installed.

![screenshot_1545101277](https://user-images.githubusercontent.com/17781268/50129067-956bd700-02cb-11e9-9bb2-3a92b948433d.png)

**Comment by roughike** [comment]
This is a problem related to setting up your app in the Facebook developer console, not an issue with this plugin.

**Comment by kudo183** [comment]
I had the same issue. The real problem is with loginBehavior = FacebookLoginBehavior.webViewOnly. Because when no facebook app installed, it fallback to webView. When I try to run with loginBehaviout = webViewOnly in Android, this issue occurred. If the problem is related to Facebook app settings, so could you please point me to some guild, thanks. 

This is log in Android Studio:

W/System  ( 7715): ClassLoader referenced unknown path: /system/app/Chrome/lib/x86
D/ApplicationLoaders( 7715): ignored Vulkan layer search path /system/app/Chrome/lib/x86:/system/app/Chrome/Chrome.apk!/lib/x86:/system/lib:/vendor/lib for namespace 0xa84f8090
I/WebViewFactory( 7715): Loading com.android.chrome version 55.0.2883.91 (code 288309112)
I/cr_LibraryLoader( 7715): Time to load native libraries: 7 ms (timestamps 3307-3314)
I/cr_LibraryLoader( 7715): Expected native library version number "55.0.2883.91", actual native library version number "55.0.2883.91"
I/cr_LibraryLoader( 7715): Expected native library version number "55.0.2883.91", actual native library version number "55.0.2883.91"
I/chromium( 7715): [INFO:library_loader_hooks.cc(163)] Chromium logging enabled: level = 0, default verbosity = 0
I/cr_BrowserStartup( 7715): Initializing chromium process, singleProcess=true
D/EGL_emulation( 7715): eglCreateContext: 0x98b9ee40: maj 3 min 0 rcv 3
D/EGL_emulation( 7715): eglMakeCurrent: 0x98b9ee40: ver 3 0 (tinfo 0x98bf4210)
W/cr_media( 7715): Requires BLUETOOTH permission
I/cr_Ime  ( 7715): ImeThread is enabled.
E/libEGL  ( 7715): validate_display:99 error 3008 (EGL_BAD_DISPLAY)
D/        ( 7715): HostConnection::get() New Host Connection established 0x7cebce40, tid 7794
D/EGL_emulation( 7715): eglCreateContext: 0x88e67860: maj 3 min 0 rcv 3
D/EGL_emulation( 7715): eglMakeCurrent: 0x88e67860: ver 3 0 (tinfo 0x7cea64c0)
I/VideoCapabilities( 7715): Unsupported profile 4 for video/mp4v-es
D/EGL_emulation( 7715): eglCreateContext: 0x88e68be0: maj 3 min 0 rcv 3
D/EGL_emulation( 7715): eglMakeCurrent: 0x88e68be0: ver 3 0 (tinfo 0x7cea64c0)
D/EGL_emulation( 7715): eglMakeCurrent: 0x9d285900: ver 3 0 (tinfo 0x9d283480)
D/EGL_emulation( 7715): eglMakeCurrent: 0x9d285900: ver 3 0 (tinfo 0x9d283480)
E/chromium( 7715): [ERROR:interface_registry.cc(104)] Failed to locate a binder for interface: autofill::mojom::PasswordManagerDriver
D/EGL_emulation( 7715): eglMakeCurrent: 0x9d285900: ver 3 0 (tinfo 0x9d283480)
W/cr_BindingManager( 7715): Cannot call determinedVisibility() - never saw a connection for the pid: 7715
I/art     ( 7715): Background partial concurrent mark sweep GC freed 44575(2MB) AllocSpace objects, 9(180KB) LOS objects, 39% free, 3MB/6MB, paused 5.948ms total 118.482ms
E/chromium( 7715): [ERROR:interface_registry.cc(104)] Failed to locate a binder for interface: autofill::mojom::PasswordManagerDriver

**Comment by buidan** [comment]
I found a working solution by add some extra code to AppDelegate.swift

```
override func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
         if url.scheme == "fbXXXXXXXXX" {
                return ApplicationDelegate.shared.application(app, open: url, options: options)
         }
        .....
    }

```
Relace XXXXXXXXX with your facebook ID
